### PR TITLE
Android: Updated for all events

### PR DESCRIPTION
**Pull request by MathiasVandePol**
I added subscribe methods for every sensor in the MSBand2. I've added hardware and firmware versioninfo too.
I also added some extra error checking and added more info to the heartrate sensor (quality)
I also removed the initiate method and added this to the connect method as i thought the inititiate method was obsolete. I also updated the band sdk to the latest version.
I've done this in just a couple of hours, only in the android project . This means that iOS does not work atm. I've just created this pull request so you could copy some of my code and update your package.

### CODE REVIEW

**Comment by wshaheer** [comment]
@MathiasVandePol: I apologize but I haven't had the chance to take a look at the pull request till today. I'll review and merge it as soon as possible.

**Comment by wshaheer** [comment]
@MathiasVandePol: I've roughly gone through your pull request and for the most part it looks fine. However, in the msband.js file you've added and additional 'subscribeWithArg'. Is it possible to just add an extra parameter to the pre-existing 'subscribe' method?

**Comment by MathiasVandePol** [comment]
I've removed the obsolete method and added it to the subscribe method. I havn't had the chance to test it yet as I have no band available to test atm.

**Comment by xrnm** [comment]
I have cloned @MathiasVandePol's fork and am using that in my production app because it is in better shape than source repo.
+1 @MathiasVandePol  You saved my bacon with this request. Thanks a million

**Pull request closed without merging**
